$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
ignorePaths:
  - "**/*.env*"
  - bun.lock
  - LICENSE
  - node_modules
words:
  - addgroup
  - adduser
  - alives
  - biomejs
  - Bunfig
  - bunx
  - cloudflared
  - CSPRNG
  - cuda
  - envfile
  - fastcgi
  - Filenaming
  - finalizer
  - ggml
  - gguf
  - Gibibyte
  - healthcheck
  - huggingface
  - keepalive
  - lefthook
  - lefthookrc
  - libgcc
  - libstdc
  - logfmt
  - loglevel
  - memlock
  - millis
  - mlock
  - mmap
  - mmproj
  - multimodal
  - ngram
  - nodelay
  - nosniff
  - openagent
  - opencode
  - oven
  - pids
  - postconditions
  - qwen
  - Qwik
  - recognised
  - rocm
  - scgi
  - seccomp
  - Somes
  - tmpfs
  - ubatch
  - ulimits
  - ultrabrain
  - unsloth
  - uwsgi
