$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
ignorePaths:
  - "**/*.env*"
  - bun.lock
  - LICENSE
  - node_modules
words:
  - biomejs
  - bunx
  - cloudflared
  - CSPRNG
  - cuda
  - envfile
  - fastcgi
  - Filenaming
  - finalizer
  - ggml
  - gguf
  - Gibibyte
  - healthcheck
  - huggingface
  - keepalive
  - lefthook
  - lefthookrc
  - loglevel
  - memlock
  - millis
  - mlock
  - mmap
  - mmproj
  - ngram
  - nodelay
  - nosniff
  - opencode
  - pids
  - postconditions
  - qwen
  - Qwik
  - rocm
  - scgi
  - seccomp
  - Somes
  - tmpfs
  - ubatch
  - ulimits
  - unsloth
  - uwsgi
